nba_teams = [
("TOR","Toronto Raptors"),
("BOS","Boston Celtics"),
("NYK","New York Knicks"),
("BRK","Brooklyn Nets"),
("PHI","Philadelphia 76ers"),
("CLE","Cleveland Cavaliers"),
("IND","Indiana Pacers"),
("DET","Detroit Pistons"),
("CHI","Chicago Bulls"),
("MIL","Milwaukee Bucks"),
("MIA","Miami Heat"),
("ATL","Atlanta Hawks"),
("CHO","Charlotte Hornets"),
("WAS","Washington Wizards"),
("ORL","Orlando Magic"),
("OKC","Oklahoma City Thunder"),
("POR","Portland Trail Blazers"),
("UTA","Utah Jazz"),
("DEN","Denver Nuggets"),
("MIN","Minnesota Timberwolves"),
("GSW","Golden State Warriors"),
("LAC","Los Angeles Clippers"),
("SAC","Sacramento Kings"),
("PHO","Phoenix Suns"),
("LAL","Los Angeles Lakers"),
("SAS","San Antonio Spurs"),
("DAL","Dallas Mavericks"),
("MEM","Memphis Grizzlies"),
("HOU","Houston Rockets"),
("NOP","New Orleans Pelicans")]